In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
#access the wikipedia table
url='https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
r=requests.get(url).text
soup = BeautifulSoup(r,'html')
table=soup.find_all('table')
df=pd.read_html(str(table))[0]

In [4]:
#The dataframe will consist of three columns: PostalCode, Borough, and Neighborhood
df1=df.rename(columns={"Postal Code":"PostalCode","Neighbourhood":"Neighborhood"})

In [7]:
#Ignore cells with a borough that is 'Not assigned'
df2=df1[df.Borough != "Not assigned"]
df3=df2.reset_index()
df3

,index,PostalCode,Borough,Neighborhood
0,2,M3A,North York,Parkwoods
1,3,M4A,North York,Victoria Village
2,4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
3,5,M6A,North York,"Lawrence Manor, Lawrence Heights"
4,6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...,...
98,160,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
99,165,M4Y,Downtown Toronto,Church and Wellesley
100,168,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
101,169,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
102,178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

In [8]:
#Combine neighborhoods based on post code
df4=df3.groupby("PostalCode")["Neighborhood"].agg([("Neighborhood", ','.join)]).reset_index()
df4

    PostalCode                                       Neighborhood
0          M1B                                     Malvern, Rouge
1          M1C             Rouge Hill, Port Union, Highland Creek
2          M1E                  Guildwood, Morningside, West Hill
3          M1G                                             Woburn
4          M1H                                          Cedarbrae
..         ...                                                ...
98         M9N                                             Weston
99         M9P                                          Westmount
100        M9R  Kingsview Village, St. Phillips, Martin Grove ...
101        M9V  South Steeles, Silverstone, Humbergate, Jamest...
102        M9W                Northwest, West Humber - Clairville

[103 rows x 2 columns]

In [13]:
#add "Borough" column
df5=pd.merge(df4,df3,on="PostalCode")
df5

,PostalCode,Neighborhood_x,index,Borough,Neighborhood_y
0,M1B,"Malvern, Rouge",9,Scarborough,"Malvern, Rouge"
1,M1C,"Rouge Hill, Port Union, Highland Creek",18,Scarborough,"Rouge Hill, Port Union, Highland Creek"
2,M1E,"Guildwood, Morningside, West Hill",27,Scarborough,"Guildwood, Morningside, West Hill"
3,M1G,Woburn,36,Scarborough,Woburn
4,M1H,Cedarbrae,45,Scarborough,Cedarbrae
...,...,...,...,...,...
98,M9N,Weston,98,York,Weston
99,M9P,Westmount,107,Etobicoke,Westmount
100,M9R,"Kingsview Village, St. Phillips, Martin Grove ...",116,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ..."
101,M9V,"South Steeles, Silverstone, Humbergate, Jamest...",143,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest..."
102,M9W,"Northwest, West Humber - Clairville",152,Etobicoke,"Northwest, West Humber - Clairville"

In [22]:
df6=df5.drop(["Neighborhood_x","index"],axis=1 )

    PostalCode      Borough                                     Neighborhood_y
0          M1B  Scarborough                                     Malvern, Rouge
1          M1C  Scarborough             Rouge Hill, Port Union, Highland Creek
2          M1E  Scarborough                  Guildwood, Morningside, West Hill
3          M1G  Scarborough                                             Woburn
4          M1H  Scarborough                                          Cedarbrae
..         ...          ...                                                ...
98         M9N         York                                             Weston
99         M9P    Etobicoke                                          Westmount
100        M9R    Etobicoke  Kingsview Village, St. Phillips, Martin Grove ...
101        M9V    Etobicoke  South Steeles, Silverstone, Humbergate, Jamest...
102        M9W    Etobicoke                Northwest, West Humber - Clairville

[103 rows x 3 columns]

In [23]:
df7=df6.rename(columns={"Neighborhood_y":"Neighborhood"})
df7

    PostalCode      Borough                                       Neighborhood
0          M1B  Scarborough                                     Malvern, Rouge
1          M1C  Scarborough             Rouge Hill, Port Union, Highland Creek
2          M1E  Scarborough                  Guildwood, Morningside, West Hill
3          M1G  Scarborough                                             Woburn
4          M1H  Scarborough                                          Cedarbrae
..         ...          ...                                                ...
98         M9N         York                                             Weston
99         M9P    Etobicoke                                          Westmount
100        M9R    Etobicoke  Kingsview Village, St. Phillips, Martin Grove ...
101        M9V    Etobicoke  South Steeles, Silverstone, Humbergate, Jamest...
102        M9W    Etobicoke                Northwest, West Humber - Clairville

[103 rows x 3 columns]

In [24]:
#if a Borough cell has a cell but a "Not assigned" Neighborhood to make Neighborhood as as Borough
#check "Not assigned" Neighborhood
df7.loc[df7["Neighborhood"] == "Not assigned"]
#since no output which means no "Not assigned" Neighborhood exists

Empty DataFrame
Columns: [PostalCode, Borough, Neighborhood]
Index: []

In [25]:
#display the table
df7

    PostalCode      Borough                                       Neighborhood
0          M1B  Scarborough                                     Malvern, Rouge
1          M1C  Scarborough             Rouge Hill, Port Union, Highland Creek
2          M1E  Scarborough                  Guildwood, Morningside, West Hill
3          M1G  Scarborough                                             Woburn
4          M1H  Scarborough                                          Cedarbrae
..         ...          ...                                                ...
98         M9N         York                                             Weston
99         M9P    Etobicoke                                          Westmount
100        M9R    Etobicoke  Kingsview Village, St. Phillips, Martin Grove ...
101        M9V    Etobicoke  South Steeles, Silverstone, Humbergate, Jamest...
102        M9W    Etobicoke                Northwest, West Humber - Clairville

[103 rows x 3 columns]

In [27]:
#print the number of rows using .shape
df7.shape

(103, 3)